baseURL = 'https://enochyu-official.github.io/blog/'
languageCode = 'en-US'
title = "Enoch Yu (유에녹)"
theme = 'EnochBlogTheme'

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[params]
  author = "Enoch Yu"
  avatar = "/images/avatar.png"
  mainSections = ["posts"]
  favicon = "favicon.ico"

[params.article]
  math = true

[params.social]
  github = "https://github.com/enochyu-official"
  youtube = "https://www.youtube.com/channel/UCCnkn0YRKStraznc7kuICRg"
  linkedin = "linkedin.com"
  email = "your@email.com"

[params.comments]
  enabled = true
  provider = "giscus"

[params.comments.giscus]
  repo = "enochyu-official/blog"
  repoID = "R_kgDOQmE9xg"
  category = "General"
  categoryID = "DIC_kwDOQmE9xs4Czr9C"
  mapping = "pathname"
  theme = "auto"
  lang = "en"

[taxonomies]
  category = "categories"
  tag      = "tags"

[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4
    ordered = false
  [markup.highlight]

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Archives"
  url = "/page/archives/"
  weight = 2

[[menu.main]]
  name = "Math"
  url = "/categories/math/"
  weight = 3

[[menu.main]]
  name = "Computer Science"
  url = "/categories/computer-science/"
  weight = 4

[[menu.main]]
  name = "Student Life"
  url = "/categories/student-life/"
  weight = 5

[[menu.main]]
  name = "Miscellaneous"
  url = "/categories/miscellaneous/"
  weight = 6
