baseURL = 'https://enochyu-official.github.io/blog/'
languageCode = 'en-us'
title = "Enoch Yu"
theme = 'hugo-theme-stack'

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[params]
mainSections = ["posts"]
themeStyle = "dark"

[params.article]
math = true

[params.sidebar]
subtitle = "Welcome to my blog!!"
emoji    = "ðŸ‡°ðŸ‡·"

[params.sidebar.avatar]
enabled = true
local   = false
src     = "images/profile.png"

[taxonomies]
category = "categories"
tag      = "tags"

#Home
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[menu.main.params]
icon = "home"

#Archives
[[menu.main]]
name = "Archives"
url = "/archives/"
weight = 2
[menu.main.params]
icon = "archives"

#Math
[[menu.main]]
name = "Math"
url = "/categories/math/"
weight = 3
[menu.main.params]
icon = "item"

#Linux
[[menu.main]]
name = "Linux"
url = "/categories/linux/"
weight = 4
[menu.main.params]
icon = "item"

#CTF
[[menu.main]]
name = "CTF"
url = "/categories/ctf/"
weight = 5
[menu.main.params]
icon = "item"

#Miscellaneous
[[menu.main]]
name = "Miscellaneous"
url = "/categories/miscellaneous/"
weight = 6
[menu.main.params]
icon = "item"

#Youtube
[[menu.social]]
identifier = "youtube"
name       = "Youtube"
url        = "https://www.youtube.com/channel/UCCnkn0YRKStraznc7kuICRg"
weight     = 1
[menu.social.params]
icon = "brand-youtube"

#Github
[[menu.social]]
identifier = "github"
name       = "GitHub"
url        = "https://github.com/enochyu-official"
weight     = 2
[menu.social.params]
icon = "brand-github"
