baseURL = 'https://enochyu-blog.pages.dev'
languageCode = 'en-US'
title = "Enoch Yu (유에녹)"
theme = 'EnochBlogTheme'

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
enableRobotsTXT = true

[params]
  author = "Enoch Yu"
  avatar = "/images/avatar.png"
  mainSections = ["posts"]
  favicon = "favicon.ico"
  math = true

[params.social]
  youtube = "https://www.youtube.com/channel/UCCnkn0YRKStraznc7kuICRg"
  github = "https://github.com/enochyu-official"
  linkedin = "https://www.linkedin.com/in/enoch-yu-94448939a/"
  email = ""

[params.comments]
  enabled = true
  provider = "giscus"

[taxonomies]
  category = "categories"
  tag      = "tags"

[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4
    ordered = false
  [markup.highlight]

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Archives"
  url = "/archives/"
  weight = 2

[[menu.main]]
  name = "Math"
  url = "/categories/math/"
  weight = 3

[[menu.main]]
  name = "Computer Science"
  url = "/categories/computer-science/"
  weight = 4

[[menu.main]]
  name = "Student Life"
  url = "/categories/student-life/"
  weight = 5

[[menu.main]]
  name = "Miscellaneous"
  url = "/categories/miscellaneous/"
  weight = 6
